### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by michaelhenry91** [michaelhenry91/codelab-sinatra-erb#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://frozen-mountain-13978.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-erb/1) criteria:
- [x] The dating profile is not necessarily for humans - questions could be catered to pets, plants, aliens, or members of a fictional universe
- [x] The root of your site (`/`) has a form to collect information that will be embedded in the dating profile
- [x] Submitting the form at the root of the site creates a new dating profile at `/profile`
- [x] One of the form inputs takes the URL of an image to be displayed on the generated profile
- [x] Any CSS or JavaScript is embedded in the page with a `style` or `script` element (we'll learn about including other files in a later lesson)
- [x](optional) For an added challenge, use [the free Formspree service](http://formspree.io/) to generate a contact form on the profile page, so that interested parties have a way of getting in touch with the creator of the profile

**Comment by chrisvfritz** [comment]
The core technical aspects of this project are absolutely perfect! 🚀  The only significant area for improvement that I see has to do with how elements are being spaced in the `.erb` files.

### The problem with `br` for spacing

The `br` element can be useful sometimes for splitting a sentence or other content onto multiple lines. For example, in an address:

``` html
<address>
  738 Oak Wood Drive<br>
  Lansing, MI 48812<br>
  USA
</address>
```

These `br` elements are not meant to control vertical spacing _between_ elements though, so whenever you're using _two or more_ `br` elements right next to each other though, you're almost always doing something wrong.

Let's take this code for example:

``` html
Paste the URL of a picture of your face
<input name="face-url"><br>
What is your face name?
<input name="face-name"><br>
<br>
What is your email address?
<input name="face-mail"><br>
<br>
```

There are a few problems with it:
- As the list of `input`s grows, we have more and more places in our code that we have to change if we decide we want to change the amount of spacing between these groups. If have 20 input groups and we want decide we want two spaces between each group, instead of one, that's 20 `br` elements that we have to add to the page.
- We can get single spaces between each group, double spaces, triple spaces, etc - but nothing in between. We don't have pixel precision.

A better strategy would be to wrap these groups in a `div`, then give that `div` a class, like this:

``` html
<div class="input-group">
  Paste the URL of a picture of your face
  <input name="face-url">
</div>
<div class="input-group">
  What is your face name?
  <input name="face-name">
</div>
<div class="input-group">
  What is your email address?
  <input name="face-mail">
</div>
```

Then for this project, you'd add some CSS to a `style` element in the `head` to control the space between input groups:

``` css
.input-group {
  margin-bottom: 15px;
}
```

That's it! You have pixel precision in adjusting spacing between elements and when you want to change that spacing, there's just one place in your CSS that you have to tweak. 😄 

Let me know if all of this makes sense.

**Comment by michaelhenry91** [comment]
This issue should now be fixed!  Here is the link again:
https://frozen-mountain-13978.herokuapp.com/

On Fri, May 27, 2016 at 11:51 AM, Chris Fritz notifications@github.com
wrote:

> The core technical aspects of this project are absolutely perfect! 🚀 The
> only significant area for improvement that I see has to do with how
> elements are being spaced in the .erb files.
> The problem with br for spacing
> 
> The br element can be useful sometimes for splitting a sentence or other
> content onto multiple lines. For example, in an address:
> 
> <address>
>   738 Oak Wood Drive<br>
>   Lansing, MI 48812<br>
>   USA
> </address>
> 
> These br elements are not meant to control vertical spacing _between_
> elements though, so whenever you're using _two or more_ br elements right
> next to each other though, you're almost always doing something wrong.
> 
> Let's take this code for example:
> 
> Paste the URL of a picture of your face
> <input name="face-url"><br>
> What is your face name?
> <input name="face-name"><br>
> <br>
> What is your email address?
> <input name="face-mail"><br>
> <br>
> 
> There are a few problems with it:
> - As the list of inputs grows, we have more and more places in our
>   code that we have to change if we decide we want to change the amount of
>   spacing between these groups. If have 20 input groups and we want decide we
>   want two spaces between each group, instead of one, that's 20 br
>   elements that we have to add to the page.
> - We can get single spaces between each group, double spaces, triple
>   spaces, etc - but nothing in between. We don't have pixel precision.
> 
> A better strategy would be to wrap these groups in a div, then give that
> div a class, like this:
> 
> <div class="input-group">
>   Paste the URL of a picture of your face
>   <input name="face-url">
> </div>
> 
> <div class="input-group">
>   What is your face name?
>   <input name="face-name">
> </div>
> 
> <div class="input-group">
>   What is your email address?
>   <input name="face-mail">
> </div>
> 
> Then for this project, you'd add some CSS to a style element in the head
> to control the space between input groups:
> 
> .input-group {
>   margin-bottom: 15px;
> }
> 
> That's it! You have pixel precision in adjusting spacing between elements
> and when you want to change that spacing, there's just one place in your
> CSS that you have to tweak. 😄
> 
> Let me know if all of this makes sense.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg63BzGHW4Wztz041S-LxN3TYB161VS4Dd4cf7P03?t=https%3A%2F%2Fgithub.com%2Fmichaelhenry91%2Fcodelab-sinatra-erb%2Fissues%2F1%23issuecomment-222183256&si=6507918181793792&pi=f757e676-71da-4004-b507-64d7ae04fdcb,
> or mute the thread
> http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg63BzGHW4Wztz041S-LxN3TYB161VS4Dd4cf7P03?t=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe%2FAFG4q9IZ1S7y6CA-R3CUMcVBBXwO99_Vks5qFxMdgaJpZM4InHc3&si=6507918181793792&pi=f757e676-71da-4004-b507-64d7ae04fdcb
> .

## 

_Michael Henry_
734.787.8505
michaelhenry91@gmail.com
_http://www.linkedin.com/in/michaelhenry91
http://www.linkedin.com/in/michaelhenry91_

**Comment by michaelhenry91** [comment]
Hello Chris!  Just wondering if you've had an opportunity to review this
revised version yet

On Mon, May 30, 2016 at 8:17 PM, Michael Henry michaelhenry91@gmail.com
wrote:

> This issue should now be fixed!  Here is the link again:
> https://frozen-mountain-13978.herokuapp.com/
> 
> On Fri, May 27, 2016 at 11:51 AM, Chris Fritz notifications@github.com
> wrote:
> 
> > The core technical aspects of this project are absolutely perfect! 🚀
> > The only significant area for improvement that I see has to do with how
> > elements are being spaced in the .erb files.
> > The problem with br for spacing
> > 
> > The br element can be useful sometimes for splitting a sentence or other
> > content onto multiple lines. For example, in an address:
> > 
> > <address>
> >   738 Oak Wood Drive<br>
> >   Lansing, MI 48812<br>
> >   USA
> > </address>
> > 
> > These br elements are not meant to control vertical spacing _between_
> > elements though, so whenever you're using _two or more_ br elements
> > right next to each other though, you're almost always doing something wrong.
> > 
> > Let's take this code for example:
> > 
> > Paste the URL of a picture of your face
> > <input name="face-url"><br>
> > What is your face name?
> > <input name="face-name"><br>
> > <br>
> > What is your email address?
> > <input name="face-mail"><br>
> > <br>
> > 
> > There are a few problems with it:
> > - As the list of inputs grows, we have more and more places in our
> >   code that we have to change if we decide we want to change the amount of
> >   spacing between these groups. If have 20 input groups and we want decide we
> >   want two spaces between each group, instead of one, that's 20 br
> >   elements that we have to add to the page.
> > - We can get single spaces between each group, double spaces, triple
> >   spaces, etc - but nothing in between. We don't have pixel precision.
> > 
> > A better strategy would be to wrap these groups in a div, then give that
> > div a class, like this:
> > 
> > <div class="input-group">
> >   Paste the URL of a picture of your face
> >   <input name="face-url">
> > </div>
> > 
> > <div class="input-group">
> >   What is your face name?
> >   <input name="face-name">
> > </div>
> > 
> > <div class="input-group">
> >   What is your email address?
> >   <input name="face-mail">
> > </div>
> > 
> > Then for this project, you'd add some CSS to a style element in the head
> > to control the space between input groups:
> > 
> > .input-group {
> >   margin-bottom: 15px;
> > }
> > 
> > That's it! You have pixel precision in adjusting spacing between elements
> > and when you want to change that spacing, there's just one place in your
> > CSS that you have to tweak. 😄
> > 
> > Let me know if all of this makes sense.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg63BzGHW4Wztz041S-LxN3TYB161VS4Dd4cf7P03?t=https%3A%2F%2Fgithub.com%2Fmichaelhenry91%2Fcodelab-sinatra-erb%2Fissues%2F1%23issuecomment-222183256&si=6507918181793792&pi=f757e676-71da-4004-b507-64d7ae04fdcb,
> > or mute the thread
> > http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg63BzGHW4Wztz041S-LxN3TYB161VS4Dd4cf7P03?t=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe%2FAFG4q9IZ1S7y6CA-R3CUMcVBBXwO99_Vks5qFxMdgaJpZM4InHc3&si=6507918181793792&pi=f757e676-71da-4004-b507-64d7ae04fdcb
> > .
> 
> ## 
> 
> _Michael Henry_
> 734.787.8505
> michaelhenry91@gmail.com
> _http://www.linkedin.com/in/michaelhenry91
> http://www.linkedin.com/in/michaelhenry91_

## 

_Michael Henry_
734.787.8505
michaelhenry91@gmail.com
_http://www.linkedin.com/in/michaelhenry91
http://www.linkedin.com/in/michaelhenry91_

**Comment by chrisvfritz** [comment]
Sorry about this! I didn't get a notification for the first comment and am still catching up this week from time off at a wedding earlier this week. The `face_mate_home.erb` file is looking much better! I still see quite a few `br`s in [`profile.erb`](https://github.com/michaelhenry91/codelab-sinatra-erb/blob/master/views/profile.erb), but you've demonstrated that you know how you'd clean it up, so let's ship it. :shipit: 😃
